# Ejercicio 7 - Indicadores

Este notebook ejecuta las consultas de `sql/07_indicadores/` sobre DuckDB y muestra la tabla que alimenta cada
indicador. La **visualizacion** se hace en Metabase (la herramienta del ambiente): el tablero se construye con
`python scripts/metabase_dashboard.py`, que usa exactamente estas consultas sobre la base materializada
`data/processed/taxis.duckdb`. Captura del tablero: `docs/dashboard/tablero.png`.

In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent / "scripts"))

import matplotlib.pyplot as plt
import pandas as pd
from lab_db import DIR_SQL, connect, leer_consulta, run_query_file

pd.set_option("display.max_columns", 30)
pd.set_option("display.width", 200)
plt.rcParams.update({"figure.figsize": (10, 4), "axes.grid": True, "grid.alpha": 0.3,
                     "axes.spines.top": False, "axes.spines.right": False})
con = connect()   # conexion en memoria + vistas de sql/00_views.sql sobre los Parquet

### `00a_kpi_viajes.sql`

- **Pregunta:** Cuantos viajes validos hay en el periodo analizado?
- **Indicador:** KPI - total de viajes validos (millones).
- **Fuente:** trips_clean

In [2]:
df, seg = run_query_file(con, DIR_SQL / "07_indicadores" / "00a_kpi_viajes.sql")
print(f"{seg:.2f} s, {len(df)} filas")
df

1.87 s, 1 filas

   viajes_millones
0             68.6

### `00b_kpi_facturacion.sql`

- **Pregunta:** Cuanto se facturo en total en el periodo analizado?
- **Indicador:** KPI - facturacion total (millones de USD).
- **Fuente:** trips_clean

In [3]:
df, seg = run_query_file(con, DIR_SQL / "07_indicadores" / "00b_kpi_facturacion.sql")
print(f"{seg:.2f} s, {len(df)} filas")
df

0.62 s, 1 filas

   facturacion_millones_usd
0                    2003.3

### `01_viajes_mensuales.sql`

- **Pregunta:** Como evoluciona la demanda de taxis mes a mes y por tipo?
- **Indicador:** Viajes validos por mes y tipo de taxi.
- **Visualizacion:** lineas (x = mes, series = tipo).
- **Fuente:** trips_clean

In [4]:
df, seg = run_query_file(con, DIR_SQL / "07_indicadores" / "01_viajes_mensuales.sql")
print(f"{seg:.2f} s, {len(df)} filas")
df

0.63 s, 40 filas

          mes taxi_type   viajes
0  2024-01-01     green    52735
1  2024-01-01    yellow  2859076
2  2024-02-01     green    49908
3  2024-02-01    yellow  2891284
4  2024-03-01     green    53581
5  2024-03-01    yellow  3427645
6  2024-04-01     green    52347
7  2024-04-01    yellow  3402039
8  2024-05-01     green    56818
9  2024-05-01    yellow  3603557
10 2024-06-01     green    51099
11 2024-06-01    yellow  3415640
12 2024-07-01     green    47964
13 2024-07-01    yellow  2961864
14 2024-08-01     green    48023
15 2024-08-01    yellow  2855227
16 2024-09-01     green    50624
17 2024-09-01    yellow  3470643
18 2024-10-01     green    52585
19 2024-10-01    yellow  3668453
20 2024-11-01     green    48560
21 2024-11-01    yellow  3496967
22 2024-12-01     green    50046
23 2024-12-01    yellow  3505036
24 2026-01-01     green    37755
25 2026-01-01    yellow  3504830
26 2026-02-01     green    34829
27 2026-02-01    yellow  3199918
28 2026-03-01     green    41350
29 2026-03-01    yellow  3749789
30 2026-04-01     green    41279
31 2026-04-01    yellow  3661836
32 2026-05-01     green    42023
33 2026-05-01    yellow  3898999
34 2026-06-01     green    41231
35 2026-06-01    yellow  3632801
36 2026-07-01     green    38241
37 2026-07-01    yellow  3333998
38 2026-08-01     green    37754
39 2026-08-01    yellow  3152409

### `02_ticket_mediano.sql`

- **Pregunta:** Cuanto paga un pasajero en un viaje tipico y como cambia en el tiempo?
- **Indicador:** Total cobrado mediano por viaje (USD), por mes y tipo.
- **Visualizacion:** lineas.
- **Fuente:** trips_clean

In [5]:
df, seg = run_query_file(con, DIR_SQL / "07_indicadores" / "02_ticket_mediano.sql")
print(f"{seg:.2f} s, {len(df)} filas")
df

1.10 s, 40 filas

          mes taxi_type  ticket_mediano_usd
0  2024-01-01     green               18.36
1  2024-01-01    yellow               20.16
2  2024-02-01     green               18.45
3  2024-02-01    yellow               20.46
4  2024-03-01     green               18.50
5  2024-03-01    yellow               20.65
6  2024-04-01     green               18.90
7  2024-04-01    yellow               21.00
8  2024-05-01     green               19.85
9  2024-05-01    yellow               21.60
10 2024-06-01     green               19.68
11 2024-06-01    yellow               21.35
12 2024-07-01     green               19.56
13 2024-07-01    yellow               21.00
14 2024-08-01     green               19.90
15 2024-08-01    yellow               21.00
16 2024-09-01     green               20.40
17 2024-09-01    yellow               21.84
18 2024-10-01     green               19.85
19 2024-10-01    yellow               21.84
20 2024-11-01     green               19.35
21 2024-11-01    yellow               21.36
22 2024-12-01     green               19.20
23 2024-12-01    yellow               21.85
24 2026-01-01     green               20.04
25 2026-01-01    yellow               23.10
26 2026-02-01     green               20.10
27 2026-02-01    yellow               24.00
28 2026-03-01     green               20.41
29 2026-03-01    yellow               23.35
30 2026-04-01     green               20.45
31 2026-04-01    yellow               23.58
32 2026-05-01     green               20.80
33 2026-05-01    yellow               23.92
34 2026-06-01     green               20.90
35 2026-06-01    yellow               23.83
36 2026-07-01     green               20.60
37 2026-07-01    yellow               23.56
38 2026-08-01     green               20.88
39 2026-08-01    yellow               23.55

### `03_uso_efectivo.sql`

- **Pregunta:** Se esta dejando de usar el efectivo?
- **Indicador:** % de viajes pagados en efectivo, sobre los viajes con metodo de pago informado (codigos 1-6).
- **Visualizacion:** lineas.
- **Fuente:** trips_clean

In [6]:
df, seg = run_query_file(con, DIR_SQL / "07_indicadores" / "03_uso_efectivo.sql")
print(f"{seg:.2f} s, {len(df)} filas")
df

0.65 s, 40 filas

          mes taxi_type  pct_efectivo
0  2024-01-01     green         30.43
1  2024-01-01    yellow         15.28
2  2024-02-01     green         29.63
3  2024-02-01    yellow         14.34
4  2024-03-01     green         30.73
5  2024-03-01    yellow         14.82
6  2024-04-01     green         28.04
7  2024-04-01    yellow         14.82
8  2024-05-01     green         28.03
9  2024-05-01    yellow         14.82
10 2024-06-01     green         27.91
11 2024-06-01    yellow         14.69
12 2024-07-01     green         28.13
13 2024-07-01    yellow         15.92
14 2024-08-01     green         27.85
15 2024-08-01    yellow         16.20
16 2024-09-01     green         26.70
17 2024-09-01    yellow         13.77
18 2024-10-01     green         26.37
19 2024-10-01    yellow         13.52
20 2024-11-01     green         25.93
21 2024-11-01    yellow         13.35
22 2024-12-01     green         26.45
23 2024-12-01    yellow         14.27
24 2026-01-01     green         23.82
25 2026-01-01    yellow         11.53
26 2026-02-01     green         23.39
27 2026-02-01    yellow         11.12
28 2026-03-01     green         22.67
29 2026-03-01    yellow         11.41
30 2026-04-01     green         22.15
31 2026-04-01    yellow         11.60
32 2026-05-01     green         22.57
33 2026-05-01    yellow         11.56
34 2026-06-01     green         22.29
35 2026-06-01    yellow         12.34
36 2026-07-01     green         21.38
37 2026-07-01    yellow         13.20
38 2026-08-01     green         23.08
39 2026-08-01    yellow         13.37

### `04_propina_tarjeta.sql`

- **Pregunta:** Que tan generosos son los pasajeros que pagan con tarjeta?
- **Indicador:** Propina mediana como % de la tarifa base en pagos con tarjeta, por anio y tipo.
- **Visualizacion:** barras agrupadas.
- **Fuente:** trips_clean (payment_type = 1)

In [7]:
df, seg = run_query_file(con, DIR_SQL / "07_indicadores" / "04_propina_tarjeta.sql")
print(f"{seg:.2f} s, {len(df)} filas")
df

1.25 s, 4 filas

   anio taxi_type  propina_mediana_pct
0  2024     green                23.49
1  2024    yellow                25.88
2  2026     green                23.64
3  2026    yellow                26.41

### `05_velocidad_por_hora.sql`

- **Pregunta:** A que hora es mas lenta la ciudad y cambio la congestion entre anios?
- **Indicador:** Velocidad mediana (mph) de taxis amarillos por hora del dia, lunes a viernes, por anio.
- **Visualizacion:** lineas (x = hora, series = anio).
- **Fuente:** trips_clean (taxi_type = 'yellow', isodow <= 5)

In [8]:
df, seg = run_query_file(con, DIR_SQL / "07_indicadores" / "05_velocidad_por_hora.sql")
print(f"{seg:.2f} s, {len(df)} filas")
df

0.76 s, 48 filas

    hora  anio  velocidad_mediana_mph
0      0  2024                  13.42
1      0  2026                  13.40
2      1  2024                  14.11
3      1  2026                  14.35
4      2  2024                  14.29
5      2  2026                  14.86
6      3  2024                  15.08
7      3  2026                  15.52
8      4  2024                  17.30
9      4  2026                  16.79
10     5  2024                  16.15
11     5  2026                  15.76
12     6  2024                  13.54
13     6  2026                  13.33
14     7  2024                  10.72
15     7  2026                  10.62
16     8  2024                   8.75
17     8  2026                   8.81
18     9  2024                   8.19
19     9  2026                   8.10
20    10  2024                   7.88
21    10  2026                   7.68
22    11  2024                   7.49
23    11  2026                   7.32
24    12  2024                   7.56
25    12  2026                   7.40
26    13  2024                   7.79
27    13  2026                   7.57
28    14  2024                   7.71
29    14  2026                   7.56
30    15  2024                   7.67
31    15  2026                   7.41
32    16  2024                   7.97
33    16  2026                   7.63
34    17  2024                   7.98
35    17  2026                   7.72
36    18  2024                   8.36
37    18  2026                   8.11
38    19  2024                   9.18
39    19  2026                   8.82
40    20  2024                   9.93
41    20  2026                   9.73
42    21  2024                  10.38
43    21  2026                  10.05
44    22  2024                  10.79
45    22  2026                  10.49
46    23  2024                  11.53
47    23  2026                  11.32

### `06_cargos_congestion.sql`

- **Pregunta:** Cuanto pesan los cargos por congestion en lo que paga el pasajero?
- **Indicador:** % de la facturacion de taxis amarillos que corresponde al recargo de congestion y al cargo CBD, por mes.
- **Visualizacion:** area apilada.
- **Fuente:** trips_clean (taxi_type = 'yellow')

In [9]:
df, seg = run_query_file(con, DIR_SQL / "07_indicadores" / "06_cargos_congestion.sql")
print(f"{seg:.2f} s, {len(df)} filas")
df

0.59 s, 20 filas

          mes  pct_recargo_congestion  pct_cargo_cbd
0  2024-01-01                    8.18           0.00
1  2024-02-01                    8.15           0.00
2  2024-03-01                    7.48           0.00
3  2024-04-01                    7.31           0.00
4  2024-05-01                    7.16           0.00
5  2024-06-01                    7.19           0.00
6  2024-07-01                    7.21           0.00
7  2024-08-01                    7.15           0.00
8  2024-09-01                    6.88           0.00
9  2024-10-01                    7.18           0.00
10 2024-11-01                    7.42           0.00
11 2024-12-01                    7.29           0.00
12 2026-01-01                    5.39           1.80
13 2026-02-01                    5.21           1.75
14 2026-03-01                    5.69           1.78
15 2026-04-01                    5.92           1.79
16 2026-05-01                    5.68           1.64
17 2026-06-01                    5.71           1.83
18 2026-07-01                    5.67           1.93
19 2026-08-01                    5.61           1.93

### `07_aeropuertos.sql`

- **Pregunta:** Que tan dependientes son los taxis amarillos de los viajes de aeropuerto?
- **Indicador:** % de viajes y % de facturacion de taxis amarillos con origen o destino en JFK, LaGuardia o Newark, por anio.
- **Visualizacion:** barras agrupadas.
- **Fuente:** trips_clean + zones

In [10]:
df, seg = run_query_file(con, DIR_SQL / "07_indicadores" / "07_aeropuertos.sql")
print(f"{seg:.2f} s, {len(df)} filas")
df

0.84 s, 2 filas

   anio  pct_viajes  pct_facturacion
0  2024       10.07            27.80
1  2026        8.11            20.94

### `08_top_zonas_origen.sql`

- **Pregunta:** Donde se concentra la demanda de taxis?
- **Indicador:** 10 zonas con mas recogidas (ambos tipos, todo el periodo) y su % del total.
- **Visualizacion:** barras horizontales.
- **Fuente:** trips_clean + zones

In [11]:
df, seg = run_query_file(con, DIR_SQL / "07_indicadores" / "08_top_zonas_origen.sql")
print(f"{seg:.2f} s, {len(df)} filas")
df

1.43 s, 10 filas

                                       zona   viajes  pct_del_total
0         Upper East Side South (Manhattan)  3118696           4.54
1                Midtown Center (Manhattan)  3027360           4.41
2                      JFK Airport (Queens)  2961000           4.32
3         Upper East Side North (Manhattan)  2804357           4.09
4                  Midtown East (Manhattan)  2241856           3.27
5  Penn Station/Madison Sq West (Manhattan)  2189484           3.19
6     Times Sq/Theatre District (Manhattan)  2149868           3.13
7           Lincoln Square East (Manhattan)  2089278           3.04
8                LaGuardia Airport (Queens)  1969166           2.87
9                   Murray Hill (Manhattan)  1873253           2.73

### `09_participacion_verdes.sql`

- **Pregunta:** Que peso tienen los taxis verdes dentro del total de viajes y esta cambiando?
- **Indicador:** % de los viajes de cada mes que hacen los taxis verdes.
- **Visualizacion:** linea.
- **Fuente:** trips_clean

In [12]:
df, seg = run_query_file(con, DIR_SQL / "07_indicadores" / "09_participacion_verdes.sql")
print(f"{seg:.2f} s, {len(df)} filas")
df

0.50 s, 20 filas

          mes  pct_verdes
0  2024-01-01       1.811
1  2024-02-01       1.697
2  2024-03-01       1.539
3  2024-04-01       1.515
4  2024-05-01       1.552
5  2024-06-01       1.474
6  2024-07-01       1.594
7  2024-08-01       1.654
8  2024-09-01       1.438
9  2024-10-01       1.413
10 2024-11-01       1.370
11 2024-12-01       1.408
12 2026-01-01       1.066
13 2026-02-01       1.077
14 2026-03-01       1.091
15 2026-04-01       1.115
16 2026-05-01       1.066
17 2026-06-01       1.122
18 2026-07-01       1.134
19 2026-08-01       1.183

### `10_pago_sin_dato.sql`

- **Pregunta:** Que tan confiable es el dato del metodo de pago?
- **Indicador:** % de viajes sin metodo de pago informado (payment_type nulo o 0) por mes y tipo.
- **Visualizacion:** lineas.
- **Fuente:** trips_clean

In [13]:
df, seg = run_query_file(con, DIR_SQL / "07_indicadores" / "10_pago_sin_dato.sql")
print(f"{seg:.2f} s, {len(df)} filas")
df

0.64 s, 40 filas

          mes taxi_type  pct_pago_sin_dato
0  2024-01-01     green               6.20
1  2024-01-01    yellow               4.02
2  2024-02-01     green               5.67
3  2024-02-01    yellow               5.14
4  2024-03-01     green               3.81
5  2024-03-01    yellow              10.64
6  2024-04-01     green               3.69
7  2024-04-01    yellow              11.40
8  2024-05-01     green               3.24
9  2024-05-01    yellow              10.69
10 2024-06-01     green               3.57
11 2024-06-01    yellow              11.33
12 2024-07-01     green               3.21
13 2024-07-01    yellow               8.87
14 2024-08-01     green               3.19
15 2024-08-01    yellow               8.34
16 2024-09-01     green               3.24
17 2024-09-01    yellow              12.39
18 2024-10-01     green               3.00
19 2024-10-01    yellow               9.40
20 2024-11-01     green               3.12
21 2024-11-01    yellow               9.59
22 2024-12-01     green               3.80
23 2024-12-01    yellow               8.24
24 2026-01-01     green              12.72
25 2026-01-01    yellow              28.35
26 2026-02-01     green              13.67
27 2026-02-01    yellow              28.98
28 2026-03-01     green              14.23
29 2026-03-01    yellow              22.88
30 2026-04-01     green              13.51
31 2026-04-01    yellow              20.17
32 2026-05-01     green              11.92
33 2026-05-01    yellow              22.50
34 2026-06-01     green              13.62
35 2026-06-01    yellow              25.35
36 2026-07-01     green              14.45
37 2026-07-01    yellow              26.29
38 2026-08-01     green              14.50
39 2026-08-01    yellow              26.58

![Tablero en Metabase](../docs/dashboard/tablero.png)